services:
  - type: web
    name: jb-soluciones-inmobiliarias
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node .output/server/index.mjs
    autoDeploy: true
